REPO_SCHEMA = {
    "repo_id": "string",
    "created_at": "timestamp",
    "updated_at": "timestamp",
    "language": "string",
    "stargazers_count": "int32",
    "forks_count": "int32",
    "size": "int64",
    "owner_type": "string",
    "description": "string",
    "has_wiki": "bool",
    "has_pages": "bool",
    "code_lines": "int32",
    "packages": "list<string>",
    "contributors": "list<string>",
    "contributor_count": "int32",
    "category": "string",
    "is_fork": "bool",
    "parent_repo": "string",
}
